services:
  postgres:
    container_name: cine_db_containerV1
    image: postgres:15
    environment:
      POSTGRES_USER: cine_user
      POSTGRES_PASSWORD: cine_password
      POSTGRES_DB: cine_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      # Credenciales para acceder a la web de pgAdmin (puedes cambiarlas)
      PGADMIN_DEFAULT_EMAIL: admin@cine.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: